### ISSUE TITLE
s3 sleep seems broken on Windows too

### ISSUE THREAD

**Issue by naveenjohnsonv** [abvee/asus-s15-vivobook-oled#1]
I have a K3502 variant. Read your [tweaks for power saving](https://github.com/abvee/asus-s15-vivobook-oled/tree/master/power-saving#problems-with-sleep) and I noticed the same issue when I tried to enable s3 sleep on Windows . Re-enabling s0 sleep fixes it too. So it seems it's not a Linux problem in particular. Found another [thread](https://zentalk.asus.com/t5/zenbook/zenbook-13-ux325-fn-keys-not-working-after-sleep-anyone/m-p/78104) discussing the same problem on a Zenbook and it's newer variant so I'm sure it's a firmware issue plaguing multiple ASUS laptops at the moment.

**Comment by abvee** [comment]
Thanks for the input :D 

I'll go through the thread and update the README file. If you find anything else, please inform me by opening another issue

**Comment by abvee** [comment]
Marking as closed. If you want to open a pull request so you can show up in commit history, I'll be happy to merge.

**Comment by naveenjohnsonv** [comment]
Did you try disabling Intel VMD Controller in UEFI/BIOS? If you haven't, try it. That should enable Link State Power Management for the SSD and should significantly improve idle drain. And if you can get S0 sleep to work in Arch as well then overnight idle should also be better. Otherwise you can instead hibernate on closing lid, I find it to be fast enough to not affect my use case. 

> Marking as closed. If you want to open a pull request so you can show up in commit history, I'll be happy to merge.

Thanks for the mention! Glad to help.
